### ISSUE TITLE
Error pushing staging branch

### ISSUE THREAD

**Issue by juanlucky** [gregoiredupe/aikido-nantes#19]
Pb de droit d'écriture ?

PS D:\Users\JuanLucky\OneDrive\Documents\Dev\aikido-nantes> git push origin staging
error: src refspec staging does not match any
error: failed to push some refs to 'https://github.com/gregoiredupe/aikido-nantes.git'

**Comment by gregoiredupe** [comment]
Essaye :

**Comment by gregoiredupe** [comment]
Essaye :  git push origin dev:staging

**Comment by juanlucky** [comment]
Ah ok, je tente ça ce soir !!

**Comment by juanlucky** [comment]
c'est passé !!c'est quoi ce besoin de préfixer avec dev: ?
