### ISSUE TITLE
Amélioration contact

### ISSUE THREAD

**Issue by juanlucky** [gregoiredupe/aikido-nantes#7]
Pas certain qu'il y ait besoin du titre de bloc "Contact"
j'aimais bien le bouton facebook centré sous le header image.
on peut mettre dessus ou dessous le n° de tél ou le mail ?

**Comment by gregoiredupe** [comment]
J'ai fait une test, cf commit 7992f7ded54168da97c0eb113d8ba1ad9836d252.
Ça me semble mieux sans le titre.

**Comment by juanlucky** [comment]
je virais bien les puces qui n'apportent pas grand chose 
juste centré 
                                   tél (police + grande ? couleur bleu ?)
                                   email (police)
                                   FB (reprendre le look du bouton de la toute première version ?)

Reprendre ce même look en bas de page, sans le titre de bloc "Contact" ?

**Comment by juanlucky** [comment]
done
